version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_2507Project
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
